### ISSUE TITLE
readme references non-public repo "neural-zoom-pt"

### ISSUE THREAD

**Issue by StoneCypher** [ProGamerGov/Neural-Zoom#1]
unclear whether this is an oversight

**Comment by ProGamerGov** [comment]
@StoneCypher It's a project that I'm currently working on it, which is intended to be a successor to Neural-Style. If you want to test it, or if you want to help me by proof-reading the `README`/`INSTALL.md` files, the code and other files can be found [here](https://gist.github.com/ProGamerGov/089a082c2a000d1e1cc034fc75ff5931).

**Comment by StoneCypher** [comment]
what's the improvement?  quality?  speed?

the images are not present

**Comment by ProGamerGov** [comment]
@StoneCypher In terms of quality, it's pretty much the exact same as the original. Though I'm using a different TV weight algorithm (because I haven't been able to get Neural-Style's TV weight setup working yet). I also haven't been able to get gradient normalization or multi-GPU strategies working yet either. Neural-Style-PT is also more memory efficient, and faster than the original.

**Comment by ProGamerGov** [comment]
@StoneCypher 

Neural-Style-PT has now been published as a public repository, here: https://github.com/ProGamerGov/neural-style-pt

I was able to also get the color independent style transfer feature from Neural-Style working as well. 

The installation guide should walk you through setting up Neural-Style-PT if you are interested in trying it out: https://github.com/ProGamerGov/neural-style-pt/blob/master/INSTALL.md
